In [6]:
from netCDF4 import Dataset
import numpy as np

In [8]:
data=Dataset(r'./precip.mon.mean.nc','r')

# data

In [9]:
print(data)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    Conventions: CF-1.0
    curator: Dr. Jian-Jian Wang
ESSIC, University of Maryland College Park
College Park, MD  20742  USA
Phone: +1 301-405-4887
    citation: Adler, R.F., G.J. Huffman, A. Chang, R. Ferraro, P. Xie, J. Janowiak, B. 
Rudolf, U. Schneider, S. Curtis, D. Bolvin, A. Gruber, J. Susskind, P. 
Arkin, 2003: The Version 2 Global Precipitation Climatology Project 
(GPCP) Monthly Precipitation Analysis (1979 - Present). J. Hydrometeor., 
4(6), 1147-1167.
    title: GPCP Version 2.3 Combined Precipitation Dataset (Final)
    platform: NOAA POES (Polar Orbiting Environmental Satellites)
    source_obs: CDR RSS SSMI/SSMIS Tbs over ocean 
CDR SSMI/SSMIS rainrates over land (Ferraro) 
Geo-IR (Xie) calibrated by SSMI/SSMIS rainrates for sampling 
TOVS/AIRS empirical precipitation estimates at higher latitudes 
(ocean and land) 
GPCC gauge analysis to bias correct satellite estimates over

# data variables

In [10]:
print(data.variables.keys())

dict_keys(['lat', 'lon', 'time_bnds', 'lat_bnds', 'lon_bnds', 'precip', 'time'])


In [11]:
precip=data.variables['precip']
print(precip)

<class 'netCDF4._netCDF4.Variable'>
float32 precip(time, lat, lon)
    long_name: Average Monthly Rate of Precipitation
    valid_range: [  0. 100.]
    units: mm/day
    add_offset: 0.0
    scale_factor: 1.0
    missing_value: -9.96921e+36
    precision: 32767
    least_significant_digit: 2
    var_desc: Precipitation
    dataset: GPCP Version 2.3 Combined Precipitation Dataset
    level_desc: Surface
    statistic: Mean
    parent_stat: Mean
    actual_range: [0.0000000e+00 2.3604587e+37]
unlimited dimensions: time
current shape = (504, 72, 144)
filling on, default _FillValue of 9.969209968386869e+36 used


In [13]:
lat=data.variables['lat']
print(lat)

<class 'netCDF4._netCDF4.Variable'>
float32 lat(lat)
    units: degrees_north
    actual_range: [ 88.75 -88.75]
    long_name: Latitude
    standard_name: latitude
    axis: Y
unlimited dimensions: 
current shape = (72,)
filling on, default _FillValue of 9.969209968386869e+36 used


In [14]:
lon=data.variables['lon']
print(lon)

<class 'netCDF4._netCDF4.Variable'>
float32 lon(lon)
    units: degrees_east
    long_name: Longitude
    actual_range: [  1.25 358.75]
    standard_name: longitude
    axis: X
unlimited dimensions: 
current shape = (144,)
filling on, default _FillValue of 9.969209968386869e+36 used


In [15]:
time=data.variables['time']
print(time)

<class 'netCDF4._netCDF4.Variable'>
float64 time(time)
    units: days since 1800-1-1 00:00:0.0
    long_name: Time
    delta_t: 0000-01-00 00:00:00
    avg_period: 0000-01-00 00:00:00
    standard_name: time
    axis: T
    actual_range: [65378. 80688.]
unlimited dimensions: time
current shape = (504,)
filling on, default _FillValue of 9.969209968386869e+36 used


In [25]:
lat_bnds=data.variables['lat_bnds']
print(lat_bnds)

<class 'netCDF4._netCDF4.Variable'>
float32 lat_bnds(lat, nv)
    units: degrees_north
    comment: latitude values at the north and south bounds of each pixel.
unlimited dimensions: 
current shape = (72, 2)
filling on, default _FillValue of 9.969209968386869e+36 used


In [26]:
lon_bnds=data.variables['lon_bnds']
print(lon_bnds)

<class 'netCDF4._netCDF4.Variable'>
float32 lon_bnds(lon, nv)
    units: degrees_east
    comment: longitude values at the west and east bounds of each pixel.
unlimited dimensions: 
current shape = (144, 2)
filling on, default _FillValue of 9.969209968386869e+36 used


In [27]:
time_bnds=data.variables['time_bnds']
print(time_bnds)

<class 'netCDF4._netCDF4.Variable'>
float32 time_bnds(time, nv)
    comment: time bounds for each time value
    units: days since 1800-01-01 00:00:00 0:00
unlimited dimensions: time
current shape = (504, 2)
filling on, default _FillValue of 9.969209968386869e+36 used


# specific variables data

In [29]:
lat_data=data.variables['lat'][:]
print(lat_data), lat_data.shape

[-88.75 -86.25 -83.75 -81.25 -78.75 -76.25 -73.75 -71.25 -68.75 -66.25
 -63.75 -61.25 -58.75 -56.25 -53.75 -51.25 -48.75 -46.25 -43.75 -41.25
 -38.75 -36.25 -33.75 -31.25 -28.75 -26.25 -23.75 -21.25 -18.75 -16.25
 -13.75 -11.25  -8.75  -6.25  -3.75  -1.25   1.25   3.75   6.25   8.75
  11.25  13.75  16.25  18.75  21.25  23.75  26.25  28.75  31.25  33.75
  36.25  38.75  41.25  43.75  46.25  48.75  51.25  53.75  56.25  58.75
  61.25  63.75  66.25  68.75  71.25  73.75  76.25  78.75  81.25  83.75
  86.25  88.75]


(None, (72,))

In [21]:
lon_data=data.variables['lon'][:]
print(lon_data),lon_data.shape

[  1.25   3.75   6.25   8.75  11.25  13.75  16.25  18.75  21.25  23.75
  26.25  28.75  31.25  33.75  36.25  38.75  41.25  43.75  46.25  48.75
  51.25  53.75  56.25  58.75  61.25  63.75  66.25  68.75  71.25  73.75
  76.25  78.75  81.25  83.75  86.25  88.75  91.25  93.75  96.25  98.75
 101.25 103.75 106.25 108.75 111.25 113.75 116.25 118.75 121.25 123.75
 126.25 128.75 131.25 133.75 136.25 138.75 141.25 143.75 146.25 148.75
 151.25 153.75 156.25 158.75 161.25 163.75 166.25 168.75 171.25 173.75
 176.25 178.75 181.25 183.75 186.25 188.75 191.25 193.75 196.25 198.75
 201.25 203.75 206.25 208.75 211.25 213.75 216.25 218.75 221.25 223.75
 226.25 228.75 231.25 233.75 236.25 238.75 241.25 243.75 246.25 248.75
 251.25 253.75 256.25 258.75 261.25 263.75 266.25 268.75 271.25 273.75
 276.25 278.75 281.25 283.75 286.25 288.75 291.25 293.75 296.25 298.75
 301.25 303.75 306.25 308.75 311.25 313.75 316.25 318.75 321.25 323.75
 326.25 328.75 331.25 333.75 336.25 338.75 341.25 343.75 346.25 348.75
 351.2

(None, (144,))

In [23]:
precip_data=data.variables['precip'][:]
print(precip_data), precip_data.shape

[[[0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  [0.         0.         0.         ... 0.         0.         0.        ]
  ...
  [0.9812404  0.9320181  0.8138066  ... 0.91615057 0.811867   0.9017285 ]
  [0.7499759  0.77453935 0.67079806 ... 0.6945452  0.73984015 0.7661884 ]
  [0.6614727  0.5773457  0.617506   ... 0.5728163  0.6059005  0.70766836]]

 [[0.33657596 0.31659493 0.32447177 ... 0.2847315  0.29603544 0.3030814 ]
  [0.2571579  0.28121045 0.28316426 ... 0.25939476 0.25399455 0.27813244]
  [0.08254394 0.10533275 0.07907505 ... 0.17585263 0.19220772 0.1084968 ]
  ...
  [1.0672555  1.1468236  1.1544616  ... 1.0722239  1.092354   1.0788598 ]
  [1.0344999  1.0159414  1.0127925  ... 0.920662   1.0546967  0.98493016]
  [0.85120386 0.9196123  0.8411766  ... 0.9757969  0.8559053  0.8240325 ]]

 [[0.27318272 0.2796247  0.18690911 ... 0.17092893 0.20687902 0.25047475]
  [0.22695705 0.261756

(None, (504, 72, 144))

In [24]:
time_data=data.variables['time'][:]
print(time_data),time_data.shape

[65378. 65409. 65437. 65468. 65498. 65529. 65559. 65590. 65621. 65651.
 65682. 65712. 65743. 65774. 65803. 65834. 65864. 65895. 65925. 65956.
 65987. 66017. 66048. 66078. 66109. 66140. 66168. 66199. 66229. 66260.
 66290. 66321. 66352. 66382. 66413. 66443. 66474. 66505. 66533. 66564.
 66594. 66625. 66655. 66686. 66717. 66747. 66778. 66808. 66839. 66870.
 66898. 66929. 66959. 66990. 67020. 67051. 67082. 67112. 67143. 67173.
 67204. 67235. 67264. 67295. 67325. 67356. 67386. 67417. 67448. 67478.
 67509. 67539. 67570. 67601. 67629. 67660. 67690. 67721. 67751. 67782.
 67813. 67843. 67874. 67904. 67935. 67966. 67994. 68025. 68055. 68086.
 68116. 68147. 68178. 68208. 68239. 68269. 68300. 68331. 68359. 68390.
 68420. 68451. 68481. 68512. 68543. 68573. 68604. 68634. 68665. 68696.
 68725. 68756. 68786. 68817. 68847. 68878. 68909. 68939. 68970. 69000.
 69031. 69062. 69090. 69121. 69151. 69182. 69212. 69243. 69274. 69304.
 69335. 69365. 69396. 69427. 69455. 69486. 69516. 69547. 69577. 69608.
 69639

(None, (504,))